Does my coding partner follow JS best practices?
amon-cofie/partner-code-review pull request #1
Opened 2022-10-03 13:14 UTC by amon-cofie

This is my pull request for peer review. I made a copy of my code from my to-do-list code for this review

2022-10-03 13:40 UTC, vflorin1995 requested changes

2022-10-03 13:40 UTC, vflorin1995 commented on src/style.css
> +  padding-right: 1rem;
Please avoid DRY. Instead, you can make one class with those two proprieties and apply it in every place you use them.

2022-10-03 13:40 UTC, vflorin1995 commented on src/style.css
> +  display: flex;
Please avoid DRY. Instead, you can make one class with those two proprieties and apply it in every place you use them.

2022-10-03 15:31 UTC, amon-cofie commented on src/style.css
> +  padding-right: 1rem;
Thank you for pointing that out. I will make the changes

2022-10-03 15:36 UTC, merged

2023-01-05 00:56 UTC, NahnahAJ commented on src/style.css
> +}
Please rewrite this code